### ISSUE TITLE
How the 4Q label is obtained?

### ISSUE THREAD

**Issue by Chenfei-Kang** [jech2/YM2413-MDB#2]
How to get the 4Q labels based on toptag? It seems that the 4Q labels in the "verified_annotation.csv" are not mapped correctly according to the relationship between toptag and 4Q?

**Comment by jech2** [comment]
I'm sorry for my late response due to my vacation and other schedules.

I checked the annotation file again, and I found that there was a mistake during generating a csv file for distribution. A line was pushed up for 4Q mapping. 
(Fortunately, there was no problem when the experiment was conducted.)

And for the tag 'exciting', we changed the name to 'fluttered' (we initially conducted annotation in Korean and the English tag name was changed in the process of discussing the appropriateness of the corresponding English tag name at the time of paper submission) but it was not reflected in the csv file when distributing the dataset.

I'm sorry for the confusion and thank you very much for letting me know the issue.

I will update the fixed version of the file in Zenodo.

Thank you,
Eunjin

**Comment by Chenfei-Kang** [comment]
> I'm sorry for my late response due to my vacation and other schedules.
> 
> I checked the annotation file again, and I found that there was a mistake during generating a csv file for distribution. A line was pushed up for 4Q mapping. (Fortunately, there was no problem when the experiment was conducted.)
> 
> And for the tag 'exciting', we changed the name to 'fluttered' (we initially conducted annotation in Korean and the English tag name was changed in the process of discussing the appropriateness of the corresponding English tag name at the time of paper submission) but it was not reflected in the csv file when distributing the dataset.
> 
> I'm sorry for the confusion and thank you very much for letting me know the issue.
> 
> I will update the fixed version of the file in Zenodo.
> 
> Thank you, Eunjin

Thank you~ ^_^
